environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu2004
  GithubApiKey:
    secure: JUUgqhJzTG2vB53phwWr4gEKcvbA8AJCvSl5UIyFpH3cUprJgoqBmmOo9hJDMIDk
  NugetApiKey:
    secure: LfXk4hZZu8ffFCrozZGc6HxI/5hZl1mN5TgiaacuWgPyJnztnXLlklxZMsMFSIe2
  APPVEYOR_RDP_PASSWORD:
    secure: 6zdOpVyE1MHV2pR5D79B1A40j2XcyRsxpwUDgW7bG4s=
  APPVEYOR_SSH_KEY: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDQHu7NW5CjEp3c4kzcSdQecJoVf2BfgF4URMTouvD3Td/3L0vTAPM6+bNvd3i/t0GzEp2kv7kALyQDrZbb5H3aTQ5wPC7b/In/De5F2BQjrgO1dfR598nnju1ELHrMLqM482BFHMkpF4zPERcNlaAZTgz45YR/cPhcZTVvXSBMen/fzxht8klj7rEkZDtWKkRzO28eHE5P3qr0zSNvKCMXpIHcsp9NnDSgM45j18yqj+iEVZBSoIVnfKuw4WPRx50AWVoy8MaYSFhch9dwe3dVXvH3ErhxnMKD6La4ydEdWJsPF6hQtGf8GIDWGwOZH1gK+DxIrJMMN4BYBfcLVTPp appveyor

  
skip_branch_with_pr: true

services:
- docker

install: 
  - sh: sudo curl -L "https://github.com/docker/compose/releases/download/1.24.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - sh: sudo chmod a+x /usr/local/bin/docker-compose

# Skip on updates to the readme.
# We can force this by adding [skip ci] or [ci skip] anywhere in commit message
skip_commits:
  message: /updated (readme|doc).*|update (readme|doc).*s/

build: false

#Kick off the CI/CD pipeline
before_test:
- cmd: |
    docker-compose -f virtual_env/docker-compose.yml up -d
    sleep 120
    docker-compose -f virtual_env/docker-compose.yml exec phpipam sed -i "s/api_allow_unsafe = false/api_allow_unsafe = true/" /var/www/html/config.php
    sleep 120
- sh: sudo docker-compose -f virtual_env/docker-compose.yml up -d
- sh: sleep 120
# try fix input device is not tty
- sh: sudo docker-compose -f virtual_env/docker-compose.yml exec -T phpipam sed -i "s/api_allow_unsafe = false/api_allow_unsafe = true/" /var/www/html/config.php
- sh: sleep 120
test_script:
# if linux , linux will using powershell core, and windows will use powershell full version
- ps: |
    if($isWindows){
      . .\build.ps1
    }else{
      sudo pwsh .\build.ps1
    }


on_failure:
 - ps: |
    if($isWindows){
      $blockRdp = $true;
      iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
    }
 - sh: |
    export APPVEYOR_SSH_BLOCK=true
    curl -sflL 'https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-ssh.sh' | bash -e -


on_success:
  - ps: |
        Invoke-psake -buildFile psake.ps1 -taskList Deploy

